# notification-service/application.yml
server:
  port: 8084

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ticketing.events"
        spring.json.type.mapping: seatHeld:com.ticketing.events.SeatHeldEvent,seatHoldExpired:com.ticketing.events.SeatHoldExpiredEvent
#        spring.json.type.mapping: >
#          seatHeld:com.ticketing.events.SeatHeldEvent,
#          seatHoldExpired:com.ticketing.events.SeatHoldExpiredEvent

logging:
  level:
    root: INFO
    com.ticketing.notification: DEBUG