apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:17-alpine
          command: ["sh", "-c", "until pg_isready -h inventory-postgres -p 5432 -U inventory_user; do echo waiting for inventory-postgres; sleep 3; done"]
        - name: wait-for-kafka
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z kafka-0.kafka.ticketing.svc.cluster.local 9092; do echo waiting for kafka; sleep 3; done"]
      containers:
        - name: inventory-service
          image: ticketing/inventory-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: INVENTORY_DB_URL
              valueFrom:
                configMapKeyRef: { name: ticketing-config, key: INVENTORY_DB_URL }
            - name: INVENTORY_DB_USERNAME
              valueFrom:
                secretKeyRef: { name: inventory-db-secret, key: POSTGRES_USER }
            - name: INVENTORY_DB_PASSWORD
              valueFrom:
                secretKeyRef: { name: inventory-db-secret, key: POSTGRES_PASSWORD }
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef: { name: ticketing-config, key: KAFKA_BOOTSTRAP_SERVERS }
          startupProbe:
            httpGet: { path: /actuator/health, port: 8082 }
            timeoutSeconds: 5
            failureThreshold: 60
            periodSeconds: 5
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8082 }
            timeoutSeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8082 }
            timeoutSeconds: 5
            periodSeconds: 20
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - port: 8082
      targetPort: 8082
