server:
  port: 8086

spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      observation-enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 300000  # 5 minutes in milliseconds

#    jpa:
#      properties:
#        hibernate:
#          jdbc:
#            time_zone: UTC

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}
  currency: ${RAZORPAY_CURRENCY:INR}

# payment-service/application.yml
resilience4j:
  circuitbreaker:
    instances:
      razorpay:
        sliding-window-size: 5
        failure-rate-threshold: 60
        wait-duration-in-open-state: 30s
        minimum-number-of-calls: 3
        record-exceptions:
          - java.io.IOException
          - com.razorpay.RazorpayException

  retry:
    instances:
      razorpay:
        max-attempts: 2
        wait-duration: 2000ms
        retry-exceptions:
          - java.io.IOException
          - com.razorpay.RazorpayException

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

logging:
  level:
    com.ticketing.payment: DEBUG
  file:
    name: logs/payment-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB

inventory-service:
  base-url: ${INVENTORY_SERVICE_URL:http://localhost:8082}