server:
  port: 8086

spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
#    jpa:
#      properties:
#        hibernate:
#          jdbc:
#            time_zone: UTC

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}
  currency: ${RAZORPAY_CURRENCY:INR}

# payment-service/application.yml
resilience4j:
  circuitbreaker:
    instances:
      razorpay:
        sliding-window-size: 5
        failure-rate-threshold: 60
        wait-duration-in-open-state: 30s
        minimum-number-of-calls: 3
        record-exceptions:
          - java.io.IOException
          - com.razorpay.RazorpayException

  retry:
    instances:
      razorpay:
        max-attempts: 2
        wait-duration: 2000ms
        retry-exceptions:
          - java.io.IOException
          - com.razorpay.RazorpayException

logging:
  level:
    com.ticketing.payment: DEBUG

inventory-service:
  base-url: ${INVENTORY_SERVICE_URL:http://localhost:8082}